Community/urls.py
from django.urls import path

from . import views
urlpatterns = [

    path('',views.community,name='community'),
    #button
    path('initiate/', views.initiate, name='initiate'),
    path('invest/', views.invest, name='invest'),


]

OR1GIN_STUDIO/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from Newsletter import views
urlpatterns = [
    path('admin/', admin.site.urls),

    #Newsletter homepage
    path('',views.home,name='home'),

    # Auth
    path('signup/', views.signupuser, name='signupuser'),
    path('login/', views.loginuser, name='loginuser'),



    #Community
    path('Community/', include('Community.urls')),

    #Projects
    path('Project/', include('Project.urls')),
    
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Project/urls.py
from django.urls import path
from . import views

app_name = 'Project'

urlpatterns = [

    path('', views.all_projects, name='all_projects'),
    path('<int:Project_id>/', views.detail, name='detail'),



]

Community/models.py
from django.db import models

# Create your models here.

Newsletter/models.py
from django.db import models

# Create your models here.
class Newsletter(models.Model):
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=1000)
    image = models.ImageField(upload_to = 'Newsletter/images/')
    url = models.URLField(blank=True)

    def __str__(self):
        return self.title

Project/models.py
from django.db import models

# Create your models here.
class Project(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    date = models.DateField()

    def __str__(self):
        return self.title

Newsletter/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


# Create your forms here.

class NewUserForm(UserCreationForm):
	email = forms.EmailField(required=True)

	class Meta:
		model = User
		fields = ("email","username","password1")

	def save(self, commit=True):
		user = super(NewUserForm, self).save(commit=False)
		user.email = self.cleaned_data['email']
		if commit:
			user.save()
		return user

Community/views.py
from django.shortcuts import render

# Create your views here.
def community(request):
    return render(request,'Community/community.html')

def initiate(request):
    return render(request,'Community/initiate.html')

def invest(request):
    return render(request,'Community/invest.html')

Newsletter/views.py
from django.shortcuts import  render, redirect
from .forms import NewUserForm
from django.contrib.auth import login, authenticate,logout
from django.contrib import messages
from django.contrib.auth.forms import AuthenticationForm
from .models import Newsletter

def home(request):
    newsletters = Newsletter.objects.all()
    return render(request,'Newsletter/home.html',{'newsletters':newsletters})

def signupuser(request):
	if request.method == "POST":
		form = NewUserForm(request.POST)
		if form.is_valid():
			user = form.save()
			login(request, user)
			messages.success(request, "Registration successful." )
			return redirect("home")
		messages.error(request, "Unsuccessful registration. Invalid information.")
	form = NewUserForm()
	return render (request=request, template_name="Newsletter/signupuser.html", context={"register_form":form})



def loginuser(request):
	if request.method == "POST":
		form = AuthenticationForm(request, data=request.POST)
		if form.is_valid():
			username = form.cleaned_data.get('username')
			password = form.cleaned_data.get('password')
			user = authenticate(username=username, password=password)
			if user is not None:
				login(request, user)
				messages.info(request, f"You are now logged in as {username}.")
				return redirect("home")
			else:
				messages.error(request,"Invalid username or password.")
		else:
			messages.error(request,"Invalid username or password.")
	form = AuthenticationForm()
	return render(request=request, template_name="Newsletter/loginuser.html", context={"login_form":form})

Project/views.py
from django.shortcuts import render, get_object_or_404
from .models import Project

# Create your views here.
def all_projects(request):
    Projects = Project.objects.order_by('-date')
    return render(request,'Project/all_projects.html',{'Projects':Projects})

def detail(request, Project_id):
    project = get_object_or_404(Project, pk=Project_id)
    return render(request, 'Project/detail.html',{'Project':project})

Community/templates/Community/community.html
{% extends "Newsletter/base.html" %}

{% block content %}
<br>
    <br>
    <br>
    <br>
    <br>
    <br>

    <div class="row justify-content-center mt-5">
            <div class="col-md-7 text-center">
                      <h5 class="card-title">BUILD FORM 0-1 WITH OUR COMMUNITY</h5>
                      <p class="text-justify">0R1GIN is empowering people with ideas, expertise, industry knowledge to initiate/participate in projects from 0-1. We will take your idea
from scratch to refine it be a promising unicorn/match you with the perfect idea based on you. You can either become an advisory roles/core
member/founder of projects after our careful evaluation and matching process.</p>
                      <a href="{% url 'initiate' %}" class="btn m-5 btn-dark btn-lg">Initiate</a>
                      <a href="{% url 'invest' %}" class="btn m-5 btn-dark btn-lg">Invest</a>

            </div>
        </div>


{% endblock %}

Community/templates/Community/initiate.html
{% extends "Newsletter/base.html" %}


{% block content %}
<br>
<br>
 <div class="col-md-4 ">

          <p>
            <iframe src="https://docs.google.com/forms/d/e/1FAIpQLSfVGK4jOh5oDqIFV2vO6j4utVapfh5MXn-nk2PlcbR87m0rFQ/viewform?embedded=true" width="1100" height="1111" frameborder="0" marginheight="0" marginwidth="0">Loading…</iframe>
          </p>

 </div>


{% endblock %}

Community/templates/Community/invest.html
{% extends "Newsletter/base.html" %}

{% block content %}


{% endblock %}

Newsletter/templates/Newsletter/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

  <link rel="icon" type="image/png" href="{% static "Newsletter/logo.png" %}">

  <title>OR1GIN STUDIO</title>
</head>

<body>

  <nav id="topNav" class="navbar navbar-expand-md navbar-light">
    <div class="container">
      <a class="navbar-brand" href="{% url 'home' %}">
        <img src="{% static "Newsletter/logo.png" %}" width="30" height="30" class="d-inline-block align-top">
        <span>OR1GIN STUDIO</span>
      </a>

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse flex-grow-1 text-right" id="navbarNav">
        <ul class="navbar-nav ml-auto flex-nowrap">
          <li class="nav-item">
            <a class="nav-link m-2" href="{% url 'home' %}">Newsletter</a>
          </li>
          <li class="nav-item">
            <a class="nav-link m-2" href="{% url 'Project:all_projects' %}">Projects</a>
          </li>
          <li class="nav-item">
            <a class="nav-link m-2" href="{% url 'community' %}" target="_blank">Community</a>
          </li>


          <li class="nav-item">
            <a role ='button' class="btn m-2 btn-dark " href="{% url 'signupuser' %}">Sign Up</a>
            <a role="button" class="btn m-2 btn-dark" href="{% url 'loginuser' %}">Login</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <div class="container">
    {% block content %}{% endblock %}
  </div>

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>

</html>

Newsletter/templates/Newsletter/home.html
{% extends "Newsletter/base.html" %}
{% load static %}

{% block content %}
<br>
    <br>
    <br>
    <br>

<div class="row justify-content-center mt-5">
        <div class="col-md-7 text-center">

                  <h1>A newsletter, Studio, and community of Founders leading the future</h1>

        </div>
    </div>
<br>
<br>




    <h3 class="mt-5">Newsletter</h3>
    <br>
    <div class="list mb-2">
      {% for newsletter in newsletters %}
      <div class="card border-0">
          <div class="row no-gutters">
            <div class="col-auto">
            {% if newsletter.url %}
            <a href="{{ newsletter.url }}">
              <img  src="{{ newsletter.image.url }}" height='200' width="400" >
            </a>
            {% else %}

            <img  src="{{ newsletter.image.url }}" height='200' width="400" >
            {% endif %}
            </div>
            <div class="col">
              <div class="card-block px-2">
                <h4 class= "pl-sm-5 card-title ">{{ newsletter.title }}</h4>
                <p class= "pl-sm-5 card-text text-justify">{{ newsletter.description }}</p>
            </div>
        </div>
      </div>
    </div>
  <br>
 {% endfor %}
</div>



{% endblock %}

Newsletter/templates/Newsletter/loginuser.html
{% extends "Newsletter/base.html" %}



{% load crispy_forms_tags %}

<!--Login-->
{% block content %}
<br>
<br>
<br>
<br>
<br>
<div class= "text-justify">
  <h3>Login</h3>
  <form method="POST" class='form-group'>
    {% csrf_token %}
    {{ login_form|crispy }}
    <p>Don't have an account? <a href="/signup">Create an account</a>.</p>
    <button class="btn btn-primary" type="submit">Login</button>

  </form>
</div>



{% endblock %}

Newsletter/templates/Newsletter/signupuser.html
{% extends "Newsletter/base.html" %}

{% block content %}

{% load crispy_forms_tags %}

<!--Register-->
<div class="container py-5">
	<h3>Sign Up</h3>
	<form method="POST">
		{% csrf_token %}
		{{ register_form|crispy }}
		<button class="btn btn-primary" type="submit">Sign Up</button>
	</form>
	<p class="text-center">If you already have an account, <a href="/login">login</a> instead.</p>
</div>

{% endblock %}

Project/templates/Project/all_projects.html
{% extends "Newsletter/base.html" %}

{% load static %}

{% block content %}
<br>
<br>
<br>
<br>
<br>

<h2 id="Projecttitle" class="font-weight-bold text-center">Projects</h2>


{% for Project in Projects %}
<div class="row justify-content-center my-3">
  <div class="col-md-10">
    <a href="{% url 'Project:detail' Project.id %}">
      <h3>{{ Project.title }}</h3>
    </a>
    <h5 class="text-muted">{{ Project.date|date:'M d Y'|upper }}</h5>
    <h4>{{ Project.description|striptags|truncatechars:100 }}</h4>
  </div>
</div>
{% endfor %}

{% endblock %}

Project/templates/Project/detail.html
{% extends "Newsletter/base.html" %}

{% load static %}

{% block content %}
<br>
<br>
<br>

<h3 class="text-center mt-5" id="projectdetailtitle">{{ Project.title }}</h3>
<br>
<h5 class="text-center text-muted mb-5">{{ Project.date|date:'F jS Y' }}</h5>

{{ Project.description|safe }}

{% endblock %}